### ISSUE TITLE
[feat] `?` help dialog

### ISSUE THREAD

**Issue by huyz** [xavierog/moulti#12]
Would be nice to have a help pop-up window when I hit `?`.
The bottom menu doesn't contain keybindings such as ⬅️ and ↩.  It took me a while to figure out how to expand/collapse an individual item without the mouse.

**Comment by xavierog** [comment]
It is true that some keybindings may not be that intuitive. Plus, a help pop-up window is quite standard in TUIs and should be relatively easy to implement.

**Comment by xavierog** [comment]
@huyz Here is a first draft, straight from my working directory:
![moulti-help-screen-0](https://github.com/user-attachments/assets/3d090f76-5a95-4a69-883c-dd51dc76344d)

Comments, suggestions?

**Comment by huyz** [comment]
@xavierog looks perfect to me. Didn't now about tab!

**Comment by xavierog** [comment]
> @xavierog looks perfect to me. Didn't know about tab!

Thanks for your feedback. I also intend to revamp the quit dialog:

Before:
![moulti-quit-dialog-old](https://github.com/user-attachments/assets/d2325723-f1ab-40d2-a2a9-c727fa49459c)

After:
![moulti-quit-dialog-new](https://github.com/user-attachments/assets/424d8194-5135-435c-9af2-3fa0071557d0)

**Comment by huyz** [comment]
Yeah that's better.

I would leave `Do not quit` as a a default color, e.g. gray, as it's for a reversal of user intent and should thus be a rare occurrence and shouldn't grab so much attention.

**Comment by xavierog** [comment]
I'll think about it. My initial intent was to use a traffic light pattern to reflect the security inherent to each option:

- not quitting is the _safest_ option as it involves no data loss whatsoever, hence the green color.
- terminating the process is potentially dangerous depending on what it does, how it was designed and how it was implemented, hence the red color.
- quitting and leaving the process untouched is a gentler option, hence the orange color.

**Comment by huyz** [comment]
IMHO, the traffic light pattern further confuses. "Green" means "go"—i.e., go with my original intent.  Which isn't what we'd want to convey

**Comment by xavierog** [comment]
That makes sense.

![moulti-quit-dialog-new-2](https://github.com/user-attachments/assets/4f2dee6c-f331-4460-a06d-148810f52559)

**Comment by xavierog** [comment]
The help dialog and the revamped quit dialog are available as of Moulti v1.13.0, released on 2024-07-21.

**Comment by xavierog** [comment]
FYI, [Textual 0.77](https://github.com/Textualize/textual/releases/tag/v0.77.0) introduces a help panel that is slightly different (it appears on the right side, not in the middle) but is also context-aware and exhaustive. I think it is worth switching from the help dialog discussed here to that new help panel.
